version: '3'

services:
  rdbms:
    image: mysql:latest
    volumes:
      - ./db_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=test
    ports:
      - 3306:3306